
package fi.vm.kapa.xml.rova.api.authorization.list;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "rovaAuthorizationListPortType", targetNamespace = "http://xml.vrk.fi/ws/Rova/AuthorizationList")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RovaAuthorizationListPortType {


    /**
     * 
     * @param request
     * @param response
     */
    @WebMethod
    @RequestWrapper(localName = "rovaAuthorizationListService", targetNamespace = "http://xml.vrk.fi/ws/Rova/AuthorizationList/Entities", className = "fi.vm.kapa.xml.rova.api.authorization.list.RovaAuthorizationListService")
    @ResponseWrapper(localName = "rovaAuthorizationListServiceResponse", targetNamespace = "http://xml.vrk.fi/ws/Rova/AuthorizationList/Entities", className = "fi.vm.kapa.xml.rova.api.authorization.list.RovaAuthorizationListServiceResponse")
    public void rovaAuthorizationListService(
        @WebParam(name = "request", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Request> request,
        @WebParam(name = "response", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<RovaAuthorizationListResponse> response);

}
