
package fi.vm.kapa.xml.rova.api.authorization.list;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * WSDL-file for RoVa Authorization service
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Rova_AuthorizationList_Service", targetNamespace = "http://xml.vrk.fi/ws/Rova/AuthorizationList", wsdlLocation = "/wsdl/authorizationList.wsdl")
public class RovaAuthorizationListService_Service
    extends Service
{

    private final static URL ROVAAUTHORIZATIONLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROVAAUTHORIZATIONLISTSERVICE_EXCEPTION;
    private final static QName ROVAAUTHORIZATIONLISTSERVICE_QNAME = new QName("http://xml.vrk.fi/ws/Rova/AuthorizationList", "Rova_AuthorizationList_Service");

    static {
        ROVAAUTHORIZATIONLISTSERVICE_WSDL_LOCATION = fi.vm.kapa.xml.rova.api.authorization.list.RovaAuthorizationListService_Service.class.getResource("/wsdl/authorizationList.wsdl");
        WebServiceException e = null;
        if (ROVAAUTHORIZATIONLISTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/authorizationList.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ROVAAUTHORIZATIONLISTSERVICE_EXCEPTION = e;
    }

    public RovaAuthorizationListService_Service() {
        super(__getWsdlLocation(), ROVAAUTHORIZATIONLISTSERVICE_QNAME);
    }

    public RovaAuthorizationListService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROVAAUTHORIZATIONLISTSERVICE_QNAME, features);
    }

    public RovaAuthorizationListService_Service(URL wsdlLocation) {
        super(wsdlLocation, ROVAAUTHORIZATIONLISTSERVICE_QNAME);
    }

    public RovaAuthorizationListService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROVAAUTHORIZATIONLISTSERVICE_QNAME, features);
    }

    public RovaAuthorizationListService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RovaAuthorizationListService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RovaAuthorizationListPortType
     */
    @WebEndpoint(name = "rovaAuthorizationListPort")
    public RovaAuthorizationListPortType getRovaAuthorizationListPort() {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/AuthorizationList", "rovaAuthorizationListPort"), RovaAuthorizationListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RovaAuthorizationListPortType
     */
    @WebEndpoint(name = "rovaAuthorizationListPort")
    public RovaAuthorizationListPortType getRovaAuthorizationListPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/AuthorizationList", "rovaAuthorizationListPort"), RovaAuthorizationListPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROVAAUTHORIZATIONLISTSERVICE_EXCEPTION!= null) {
            throw ROVAAUTHORIZATIONLISTSERVICE_EXCEPTION;
        }
        return ROVAAUTHORIZATIONLISTSERVICE_WSDL_LOCATION;
    }

}
