
package fi.vm.kapa.xml.rova.api.orgpersonmandates;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * WSDL-file for RoVa Organizational person mandate service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Rova_OrgPersonMandates_Service", targetNamespace = "http://xml.vrk.fi/ws/Rova/OrgPersonMandates", wsdlLocation = "/wsdl/orgpersonmandates.wsdl")
public class RovaOrgPersonMandatesService_Service
    extends Service
{

    private final static URL ROVAORGPERSONMANDATESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROVAORGPERSONMANDATESSERVICE_EXCEPTION;
    private final static QName ROVAORGPERSONMANDATESSERVICE_QNAME = new QName("http://xml.vrk.fi/ws/Rova/OrgPersonMandates", "Rova_OrgPersonMandates_Service");

    static {
        ROVAORGPERSONMANDATESSERVICE_WSDL_LOCATION = fi.vm.kapa.xml.rova.api.orgpersonmandates.RovaOrgPersonMandatesService_Service.class.getResource("/wsdl/orgpersonmandates.wsdl");
        WebServiceException e = null;
        if (ROVAORGPERSONMANDATESSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/orgpersonmandates.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ROVAORGPERSONMANDATESSERVICE_EXCEPTION = e;
    }

    public RovaOrgPersonMandatesService_Service() {
        super(__getWsdlLocation(), ROVAORGPERSONMANDATESSERVICE_QNAME);
    }

    public RovaOrgPersonMandatesService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROVAORGPERSONMANDATESSERVICE_QNAME, features);
    }

    public RovaOrgPersonMandatesService_Service(URL wsdlLocation) {
        super(wsdlLocation, ROVAORGPERSONMANDATESSERVICE_QNAME);
    }

    public RovaOrgPersonMandatesService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROVAORGPERSONMANDATESSERVICE_QNAME, features);
    }

    public RovaOrgPersonMandatesService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RovaOrgPersonMandatesService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RovaOrgPersonMandatesPortType
     */
    @WebEndpoint(name = "rovaOrgPersonMandatesServicePort")
    public RovaOrgPersonMandatesPortType getRovaOrgPersonMandatesServicePort() {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/OrgPersonMandates", "rovaOrgPersonMandatesServicePort"), RovaOrgPersonMandatesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RovaOrgPersonMandatesPortType
     */
    @WebEndpoint(name = "rovaOrgPersonMandatesServicePort")
    public RovaOrgPersonMandatesPortType getRovaOrgPersonMandatesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/OrgPersonMandates", "rovaOrgPersonMandatesServicePort"), RovaOrgPersonMandatesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROVAORGPERSONMANDATESSERVICE_EXCEPTION!= null) {
            throw ROVAORGPERSONMANDATESSERVICE_EXCEPTION;
        }
        return ROVAORGPERSONMANDATESSERVICE_WSDL_LOCATION;
    }

}
