
package fi.vm.kapa.xml.rova.api.orgmandates;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * WSDL-file for RoVa Organizational roles service
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Rova_OrgMandates_Service", targetNamespace = "http://xml.vrk.fi/ws/Rova/OrgMandates", wsdlLocation = "/wsdl/orgmandates.wsdl")
public class RovaOrgMandatesService_Service
    extends Service
{

    private final static URL ROVAORGMANDATESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROVAORGMANDATESSERVICE_EXCEPTION;
    private final static QName ROVAORGMANDATESSERVICE_QNAME = new QName("http://xml.vrk.fi/ws/Rova/OrgMandates", "Rova_OrgMandates_Service");

    static {
        ROVAORGMANDATESSERVICE_WSDL_LOCATION = fi.vm.kapa.xml.rova.api.orgmandates.RovaOrgMandatesService_Service.class.getResource("/wsdl/orgmandates.wsdl");
        WebServiceException e = null;
        if (ROVAORGMANDATESSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/orgmandates.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ROVAORGMANDATESSERVICE_EXCEPTION = e;
    }

    public RovaOrgMandatesService_Service() {
        super(__getWsdlLocation(), ROVAORGMANDATESSERVICE_QNAME);
    }

    public RovaOrgMandatesService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROVAORGMANDATESSERVICE_QNAME, features);
    }

    public RovaOrgMandatesService_Service(URL wsdlLocation) {
        super(wsdlLocation, ROVAORGMANDATESSERVICE_QNAME);
    }

    public RovaOrgMandatesService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROVAORGMANDATESSERVICE_QNAME, features);
    }

    public RovaOrgMandatesService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RovaOrgMandatesService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RovaOrgMandatesPortType
     */
    @WebEndpoint(name = "rovaOrgMandatesServicePort")
    public RovaOrgMandatesPortType getRovaOrgMandatesServicePort() {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/OrgMandates", "rovaOrgMandatesServicePort"), RovaOrgMandatesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RovaOrgMandatesPortType
     */
    @WebEndpoint(name = "rovaOrgMandatesServicePort")
    public RovaOrgMandatesPortType getRovaOrgMandatesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/OrgMandates", "rovaOrgMandatesServicePort"), RovaOrgMandatesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROVAORGMANDATESSERVICE_EXCEPTION!= null) {
            throw ROVAORGMANDATESSERVICE_EXCEPTION;
        }
        return ROVAORGMANDATESSERVICE_WSDL_LOCATION;
    }

}
