server:
  port: ${HTTP_PORT:10050}
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    feign: DEBUG
  file: ${LOG_LOCATION:/var/log/daily-update/${spring.application.name:daily-update-service}.log}

