
package fi.vm.kapa.xml.rova.api.authorization;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "rovaAuthorizationPortType", targetNamespace = "http://xml.vrk.fi/ws/Rova/Authorization")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RovaAuthorizationPortType {


    /**
     * 
     * @param request
     * @param response
     */
    @WebMethod
    @RequestWrapper(localName = "rovaAuthorizationService", targetNamespace = "http://xml.vrk.fi/ws/Rova/Authorization/Entities", className = "fi.vm.kapa.xml.rova.api.authorization.RovaAuthorizationService")
    @ResponseWrapper(localName = "rovaAuthorizationServiceResponse", targetNamespace = "http://xml.vrk.fi/ws/Rova/Authorization/Entities", className = "fi.vm.kapa.xml.rova.api.authorization.RovaAuthorizationServiceResponse")
    public void rovaAuthorizationService(
        @WebParam(name = "request", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Request> request,
        @WebParam(name = "response", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<RovaAuthorizationResponse> response);

}
