
package fi.vm.kapa.xml.rova.api.orgroles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "rovaOrganizationalRolesPortType", targetNamespace = "http://xml.vrk.fi/ws/Rova/OrgRoles")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RovaOrganizationalRolesPortType {


    /**
     * 
     * @param request
     * @param response
     */
    @WebMethod
    @RequestWrapper(localName = "rovaOrganizationalRolesService", targetNamespace = "http://xml.vrk.fi/ws/Rova/OrgRoles/Entities", className = "fi.vm.kapa.xml.rova.api.orgroles.RovaOrganizationalRolesService")
    @ResponseWrapper(localName = "rovaOrganizationalRolesServiceResponse", targetNamespace = "http://xml.vrk.fi/ws/Rova/OrgRoles/Entities", className = "fi.vm.kapa.xml.rova.api.orgroles.RovaOrganizationalRolesServiceResponse")
    public void rovaOrganizationalRolesService(
        @WebParam(name = "request", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Request> request,
        @WebParam(name = "response", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Response> response);

}
