
package fi.vm.kapa.xml.rova.api.orgroles;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * WSDL-file for RoVa Organizational roles service
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Rova_OrganizationalRoles_Service", targetNamespace = "http://xml.vrk.fi/ws/Rova/OrgRoles", wsdlLocation = "/wsdl/orgroles.wsdl")
public class RovaOrganizationalRolesService_Service
    extends Service
{

    private final static URL ROVAORGANIZATIONALROLESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROVAORGANIZATIONALROLESSERVICE_EXCEPTION;
    private final static QName ROVAORGANIZATIONALROLESSERVICE_QNAME = new QName("http://xml.vrk.fi/ws/Rova/OrgRoles", "Rova_OrganizationalRoles_Service");

    static {
        ROVAORGANIZATIONALROLESSERVICE_WSDL_LOCATION = fi.vm.kapa.xml.rova.api.orgroles.RovaOrganizationalRolesService_Service.class.getResource("/wsdl/orgroles.wsdl");
        WebServiceException e = null;
        if (ROVAORGANIZATIONALROLESSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/orgroles.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ROVAORGANIZATIONALROLESSERVICE_EXCEPTION = e;
    }

    public RovaOrganizationalRolesService_Service() {
        super(__getWsdlLocation(), ROVAORGANIZATIONALROLESSERVICE_QNAME);
    }

    public RovaOrganizationalRolesService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROVAORGANIZATIONALROLESSERVICE_QNAME, features);
    }

    public RovaOrganizationalRolesService_Service(URL wsdlLocation) {
        super(wsdlLocation, ROVAORGANIZATIONALROLESSERVICE_QNAME);
    }

    public RovaOrganizationalRolesService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROVAORGANIZATIONALROLESSERVICE_QNAME, features);
    }

    public RovaOrganizationalRolesService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RovaOrganizationalRolesService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RovaOrganizationalRolesPortType
     */
    @WebEndpoint(name = "rovaOrganizationalRolesPort")
    public RovaOrganizationalRolesPortType getRovaOrganizationalRolesPort() {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/OrgRoles", "rovaOrganizationalRolesPort"), RovaOrganizationalRolesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RovaOrganizationalRolesPortType
     */
    @WebEndpoint(name = "rovaOrganizationalRolesPort")
    public RovaOrganizationalRolesPortType getRovaOrganizationalRolesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.vrk.fi/ws/Rova/OrgRoles", "rovaOrganizationalRolesPort"), RovaOrganizationalRolesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROVAORGANIZATIONALROLESSERVICE_EXCEPTION!= null) {
            throw ROVAORGANIZATIONALROLESSERVICE_EXCEPTION;
        }
        return ROVAORGANIZATIONALROLESSERVICE_WSDL_LOCATION;
    }

}
