apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: couchbase-client
  labels:
    app: couchbase-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-client
  template:
    metadata:
      labels:
        app: couchbase-client
    spec:
      containers:
      - name: couchbase-client
        image: asarkar/couchbase-client
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: COUCHBASE_NODES
          value: couchbase.${POD_NAMESPACE}.svc.cluster.local
        - name: COUCHBASE_BUCKET_CREATE_IF_MISSING
          value: "true"
        - name: BEER_DEMO_INITIALIZE
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
