kind: Service
apiVersion: v1
metadata:
  name: couchbase-client
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: couchbase-client
