server:
  port: ${HTTP_PORT:10020}
nyt:
  ribbon:
    listOfServers: ${nyt.base-url}
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  file: ${LOG_LOCATION:/var/log/daily-update/${spring.application.name:news-service}.log}
