apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  ports:
  - port: 5701
    name: hazelcast
  clusterIP: None
  selector:
    app: hazelcast
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  selector:
    matchLabels:
      app: hazelcast
  serviceName: "hazelcast"
  replicas: 2
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast
        ports:
        - containerPort: 5701
          name: hazelcast