apiVersion: v1
kind: Service
metadata:
  labels:
    app: hazelcast-client
  name: hazelcast-client
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: hazelcast-client
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-client
  labels:
    app: hazelcast-client
spec:
  selector:
    matchLabels:
      app: hazelcast-client
  template:
    metadata:
      labels:
        app: hazelcast-client
    spec:
      containers:
        - image: hazelcast-client
          name: hazelcast-client
          imagePullPolicy: Never
          ports:
            - containerPort: 8080