
package fi.vm.kapa.xml.rova.api.delegate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "rovaDelegatePortType", targetNamespace = "http://xml.vrk.fi/ws/Rova/Delegate")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RovaDelegatePortType {


    /**
     * 
     * @param request
     * @param response
     */
    @WebMethod
    @RequestWrapper(localName = "rovaDelegateService", targetNamespace = "http://xml.vrk.fi/ws/Rova/Delegate/Entities", className = "fi.vm.kapa.xml.rova.api.delegate.RovaDelegateService")
    @ResponseWrapper(localName = "rovaDelegateServiceResponse", targetNamespace = "http://xml.vrk.fi/ws/Rova/Delegate/Entities", className = "fi.vm.kapa.xml.rova.api.delegate.RovaDelegateServiceResponse")
    public void rovaDelegateService(
        @WebParam(name = "request", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Request> request,
        @WebParam(name = "response", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Response> response);

}
